// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MapEditor {
    
    
    public partial class ObjectChooser {
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView listObjects;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MapEditor.ObjectChooser
            this.Name = "MapEditor.ObjectChooser";
            this.Title = Mono.Unix.Catalog.GetString("ObjectChooser");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child MapEditor.ObjectChooser.Gtk.Container+ContainerChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.listObjects = new Gtk.TreeView();
            this.listObjects.CanFocus = true;
            this.listObjects.Name = "listObjects";
            this.GtkScrolledWindow.Add(this.listObjects);
            this.Add(this.GtkScrolledWindow);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
        }
    }
}
