
// This file has been generated by the GUI designer. Do not modify.
namespace MapEditor
{
	public partial class TileChooser
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.Table tableTileGrid;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MapEditor.TileChooser
			this.Name = "MapEditor.TileChooser";
			this.Title = global::Mono.Unix.Catalog.GetString ("TileChooser");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowShrink = true;
			this.DefaultWidth = 200;
			this.DefaultHeight = 300;
			// Container child MapEditor.TileChooser.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.tableTileGrid = new global::Gtk.Table (((uint)(3)), ((uint)(3)), true);
			this.tableTileGrid.Name = "tableTileGrid";
			this.fixed3.Add (this.tableTileGrid);
			w1.Add (this.fixed3);
			this.scrolledwindow1.Add (w1);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
