
// This file has been generated by the GUI designer. Do not modify.
namespace MapEditor
{
	public partial class ObjectChooser
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView listObjects;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MapEditor.ObjectChooser
			this.Name = "MapEditor.ObjectChooser";
			this.Title = global::Mono.Unix.Catalog.GetString ("ObjectChooser");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MapEditor.ObjectChooser.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.listObjects = new global::Gtk.TreeView ();
			this.listObjects.CanFocus = true;
			this.listObjects.Name = "listObjects";
			this.GtkScrolledWindow.Add (this.listObjects);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
