// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MapEditor {
    
    
    public partial class TileChooser {
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.Fixed fixed3;
        
        private Gtk.Table tableTileGrid;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MapEditor.TileChooser
            this.Name = "MapEditor.TileChooser";
            this.Title = Mono.Unix.Catalog.GetString("TileChooser");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.AllowShrink = true;
            this.DefaultWidth = 200;
            this.DefaultHeight = 300;
            // Container child MapEditor.TileChooser.Gtk.Container+ContainerChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            Gtk.Viewport w1 = new Gtk.Viewport();
            w1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport.Gtk.Container+ContainerChild
            this.fixed3 = new Gtk.Fixed();
            this.fixed3.Name = "fixed3";
            this.fixed3.HasWindow = false;
            // Container child fixed3.Gtk.Fixed+FixedChild
            this.tableTileGrid = new Gtk.Table(((uint)(3)), ((uint)(3)), true);
            this.tableTileGrid.Name = "tableTileGrid";
            this.fixed3.Add(this.tableTileGrid);
            w1.Add(this.fixed3);
            this.scrolledwindow1.Add(w1);
            this.Add(this.scrolledwindow1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
