// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MapEditor {
    
    
    public partial class NewMapDialog {
        
        private Gtk.Table table1;
        
        private Gtk.ComboBox comboTileset;
        
        private Gtk.Label label1;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.Label label6;
        
        private Gtk.Label label7;
        
        private Gtk.SpinButton spinHeight;
        
        private Gtk.SpinButton spinLayers;
        
        private Gtk.SpinButton spinTilesize;
        
        private Gtk.SpinButton spinWidth;
        
        private Gtk.SpinButton spinXOffset;
        
        private Gtk.SpinButton spinYOffset;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget MapEditor.NewMapDialog
            this.Name = "MapEditor.NewMapDialog";
            this.Title = Mono.Unix.Catalog.GetString("New map");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            // Internal child MapEditor.NewMapDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(4)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(25));
            // Container child table1.Gtk.Table+TableChild
            this.comboTileset = Gtk.ComboBox.NewText();
            this.comboTileset.Name = "comboTileset";
            this.table1.Add(this.comboTileset);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.comboTileset]));
            w2.TopAttach = ((uint)(4));
            w2.BottomAttach = ((uint)(5));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(4));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Width");
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Height");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w4.TopAttach = ((uint)(1));
            w4.BottomAttach = ((uint)(2));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Layers");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w5.TopAttach = ((uint)(2));
            w5.BottomAttach = ((uint)(3));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Tileset");
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w6.TopAttach = ((uint)(4));
            w6.BottomAttach = ((uint)(5));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Tile size");
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w7.TopAttach = ((uint)(3));
            w7.BottomAttach = ((uint)(4));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 0F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("X offset");
            this.table1.Add(this.label6);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
            w8.LeftAttach = ((uint)(2));
            w8.RightAttach = ((uint)(3));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Y offset");
            this.table1.Add(this.label7);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.label7]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.LeftAttach = ((uint)(2));
            w9.RightAttach = ((uint)(3));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.spinHeight = new Gtk.SpinButton(1, 1000, 1);
            this.spinHeight.CanFocus = true;
            this.spinHeight.Name = "spinHeight";
            this.spinHeight.Adjustment.PageIncrement = 10;
            this.spinHeight.ClimbRate = 1;
            this.spinHeight.Numeric = true;
            this.spinHeight.Value = 100;
            this.table1.Add(this.spinHeight);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.spinHeight]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.spinLayers = new Gtk.SpinButton(1, 10, 1);
            this.spinLayers.CanFocus = true;
            this.spinLayers.Name = "spinLayers";
            this.spinLayers.Adjustment.PageIncrement = 10;
            this.spinLayers.ClimbRate = 1;
            this.spinLayers.Numeric = true;
            this.spinLayers.Value = 1;
            this.table1.Add(this.spinLayers);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.spinLayers]));
            w11.TopAttach = ((uint)(2));
            w11.BottomAttach = ((uint)(3));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.spinTilesize = new Gtk.SpinButton(1, 1000, 1);
            this.spinTilesize.CanFocus = true;
            this.spinTilesize.Name = "spinTilesize";
            this.spinTilesize.Adjustment.PageIncrement = 10;
            this.spinTilesize.ClimbRate = 1;
            this.spinTilesize.Numeric = true;
            this.spinTilesize.Value = 16;
            this.table1.Add(this.spinTilesize);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.spinTilesize]));
            w12.TopAttach = ((uint)(3));
            w12.BottomAttach = ((uint)(4));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.spinWidth = new Gtk.SpinButton(1, 1000, 1);
            this.spinWidth.CanFocus = true;
            this.spinWidth.Name = "spinWidth";
            this.spinWidth.Adjustment.PageIncrement = 10;
            this.spinWidth.ClimbRate = 1;
            this.spinWidth.Numeric = true;
            this.spinWidth.Value = 100;
            this.table1.Add(this.spinWidth);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.spinWidth]));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.spinXOffset = new Gtk.SpinButton(-1000, 1000, 1);
            this.spinXOffset.CanFocus = true;
            this.spinXOffset.Name = "spinXOffset";
            this.spinXOffset.Adjustment.PageIncrement = 10;
            this.spinXOffset.ClimbRate = 1;
            this.spinXOffset.Numeric = true;
            this.table1.Add(this.spinXOffset);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.spinXOffset]));
            w14.LeftAttach = ((uint)(3));
            w14.RightAttach = ((uint)(4));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.spinYOffset = new Gtk.SpinButton(-1000, 1000, 1);
            this.spinYOffset.CanFocus = true;
            this.spinYOffset.Name = "spinYOffset";
            this.spinYOffset.Adjustment.PageIncrement = 10;
            this.spinYOffset.ClimbRate = 1;
            this.spinYOffset.Numeric = true;
            this.table1.Add(this.spinYOffset);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.spinYOffset]));
            w15.TopAttach = ((uint)(1));
            w15.BottomAttach = ((uint)(2));
            w15.LeftAttach = ((uint)(3));
            w15.RightAttach = ((uint)(4));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            w1.Add(this.table1);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(w1[this.table1]));
            w16.Position = 0;
            w16.Expand = false;
            w16.Fill = false;
            // Internal child MapEditor.NewMapDialog.ActionArea
            Gtk.HButtonBox w17 = this.ActionArea;
            w17.Name = "dialog1_ActionArea";
            w17.Spacing = 10;
            w17.BorderWidth = ((uint)(5));
            w17.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w18 = ((Gtk.ButtonBox.ButtonBoxChild)(w17[this.buttonCancel]));
            w18.Expand = false;
            w18.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w19 = ((Gtk.ButtonBox.ButtonBoxChild)(w17[this.buttonOk]));
            w19.Position = 1;
            w19.Expand = false;
            w19.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 315;
            this.DefaultHeight = 236;
            this.Show();
        }
    }
}
